

sequenceDiagram
    participant navegador
    participant servidor

    Note over navegador,servidor: Previamente se cargó la página siguiendo una secuencia para <br/> obtener los archivos del servidory renderizar las notas.
    Note over navegador,servidor: Un controlador de eventos espera a que se envíe el formulario...

    navegador->>servidor: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    Note over navegador,servidor: El servidor recibe los datos del formulario, los convierte <br/> en un objeto de nota y los almacena en un arreglo con las notas.
    
    activate servidor
    servidor-->>navegador: HTTP 302: Redirección de URL
    deactivate servidor

   Note over navegador,servidor: Responde el Servidor al Navegador con instrucciones de <br/> cargar la página y obtener los archivos main.css, main.js y data.json. <br/>Enviando ahora el arreglo de las notas actualziado a través de data.json

    navegador->>servidor: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate servidor
    servidor-->>navegador: archivo css
    deactivate servidor

    navegador->>servidor: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate servidor
    servidor-->>navegador: archivo JavaScript
    deactivate servidor

    Note over navegador,servidor: EL navegador comienza a ejecturar el código de JavaScript<br/> que recupera el archivo JSON del servidor

    navegador->>servidor: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate servidor
    servidor-->>navegador: [{ "content": "HTML is easy", "date": "2023-1-1" }, ... ]
    deactivate servidor

   Note over navegador,servidor: El navegador ejecuta la función de<br/> devoluvción de llamada que renderiza las notas
